[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "numpy",
    "cython"
]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
addopts = "--cov=slapping"
testpaths = [
    "tests",
]